name: Build and Push to ECR

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/docker-build-push.yml"
  workflow_dispatch:

jobs:
  check-changes:
    name: Check Backend Changes
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for backend changes
        id: check
        run: |
          git diff --name-only HEAD^ HEAD > changes.txt
          if grep -q "^backend/" changes.txt; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Backend changes detected"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No backend changes"
          fi

  check-ecr:
    name: Check ECR Repository
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}
      repo_url: ${{ steps.check.outputs.repo_url }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check ECR repository
        id: check
        run: |
          # Get the ECR repository name from Terraform state
          ECR_REPO_NAME=$(aws s3 cp s3://${{ vars.TF_STATE_BUCKET }}/${{ vars.TF_STATE_KEY }} - | jq -r '.resources[] | select(.type=="aws_ecr_repository") | .instances[0].attributes.name')

          if [ -z "$ECR_REPO_NAME" ]; then
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "ECR repository not found in Terraform state"
            exit 0
          fi

          # Check if repository exists in ECR
          if aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" 2>/dev/null; then
            REPO_URL=$(aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" --query 'repositories[0].repositoryUri' --output text)
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT
            echo "ECR repository exists: $REPO_URL"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "ECR repository does not exist"
          fi

  build-and-push:
    name: Build and Push to ECR
    needs: [check-changes, check-ecr]
    if: needs.check-changes.outputs.has_changes == 'true' && needs.check-ecr.outputs.exists == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REPO_URL: ${{ needs.check-ecr.outputs.repo_url }}
        working-directory: ./backend
        run: |
          # Build Docker image
          docker build --no-cache -t $ECR_REPO_URL:latest .

          # Push Docker image to ECR
          docker push $ECR_REPO_URL:latest
