name: Setup ECR Repository

on:
  push:
    branches: [main]
    paths:
      - "infra/ecr.tf"
      - "infra/variables.tf"
      - ".github/workflows/ecr-setup.yml"
  workflow_dispatch:

jobs:
  verify-secrets:
    name: Verify Required Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets and variables
        run: |
          missing_items=()

          # Check secrets
          [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && missing_items+=("Secret: AWS_ACCESS_KEY_ID")
          [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] && missing_items+=("Secret: AWS_SECRET_ACCESS_KEY")

          # Check variables
          [ -z "${{ vars.AWS_REGION }}" ] && missing_items+=("Variable: AWS_REGION")
          [ -z "${{ vars.TF_STATE_BUCKET }}" ] && missing_items+=("Variable: TF_STATE_BUCKET")
          [ -z "${{ vars.TF_STATE_KEY }}" ] && missing_items+=("Variable: TF_STATE_KEY")
          [ -z "${{ vars.TF_LOCK_TABLE }}" ] && missing_items+=("Variable: TF_LOCK_TABLE")

          if [ ${#missing_items[@]} -ne 0 ]; then
            echo "Error: The following required items are missing:"
            printf '%s\n' "${missing_items[@]}"
            echo "Please add these in your GitHub repository settings"
            exit 1
          fi

          echo "All required configurations are present"

  terraform-ecr:
    name: Create ECR Repository
    needs: verify-secrets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ vars.TF_STATE_KEY }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE }}"

      - name: Terraform Plan ECR
        id: plan
        run: terraform plan -target=aws_ecr_repository.backend -out=ecr.tfplan

      - name: Terraform Apply ECR
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve ecr.tfplan
