name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.7
  TF_STATE_BUCKET: terraform-state--8806442
  TF_STATE_KEY: terraform.tfstate
  TF_LOCK_TABLE: terraform-locks-8806442

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Infrastructure Outputs
        id: tf-outputs
        working-directory: .
        run: |
          # Get S3 bucket name from Terraform state
          S3_BUCKET=$(aws s3 cp s3://${{ env.TF_STATE_BUCKET }}/${{ env.TF_STATE_KEY }} - | jq -r '.outputs.frontend_bucket_name.value')
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

          # Get CloudFront distribution ID from Terraform state
          CF_DISTRIBUTION_ID=$(aws s3 cp s3://${{ env.TF_STATE_BUCKET }}/${{ env.TF_STATE_KEY }} - | jq -r '.outputs.cloudfront_distribution_id.value')
          echo "CF_DISTRIBUTION_ID=$CF_DISTRIBUTION_ID" >> $GITHUB_ENV

          # Get CloudFront URL for API endpoint (using ALB through CloudFront)
          CLOUDFRONT_URL=$(aws s3 cp s3://${{ env.TF_STATE_BUCKET }}/${{ env.TF_STATE_KEY }} - | jq -r '.outputs.cloudfront_distribution_domain.value')
          echo "CLOUDFRONT_URL=$CLOUDFRONT_URL" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        env:
          # Remove the /api prefix as it's already included in the API calls
          VITE_API_URL: https://${{ env.CLOUDFRONT_URL }}
        run: |
          echo "Setting API URL to: https://${{ env.CLOUDFRONT_URL }}"
          npm run build

      - name: Deploy to S3
        run: |
          echo "Deploying to S3 bucket: ${{ env.S3_BUCKET }}"
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          echo "Invalidating CloudFront distribution: ${{ env.CF_DISTRIBUTION_ID }}"
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"
